ALTER TABLE "OPSOSYSTEM"."TARIF_OPTION_LINK" DROP CONSTRAINT "FK_TARIFS_TARIFS_OPTIONS_LINK"
/
ALTER TABLE "OPSOSYSTEM"."TARIF_OPTION_LINK" DROP CONSTRAINT "FK_OPTIONS_TARIFS_OPTIONS_LINK"
/
ALTER TABLE "OPSOSYSTEM"."EXCLUDE_OPTION" DROP CONSTRAINT "FK_exclude_option19"
/
ALTER TABLE "OPSOSYSTEM"."EXCLUDE_OPTION" DROP CONSTRAINT "FK_exclude_option20"
/
ALTER TABLE "OPSOSYSTEM"."INCLUDE_OPTION" DROP CONSTRAINT "FK_include_option"
/
ALTER TABLE "OPSOSYSTEM"."CONTRACT" DROP CONSTRAINT "FK_CLIENTS_CONTRACTS"
/
ALTER TABLE "OPSOSYSTEM"."CONTRACT" DROP CONSTRAINT "FK_TARIFS_CONTRACTS"
/
ALTER TABLE "OPSOSYSTEM"."CONTRACT" DROP CONSTRAINT "FK_contract21"
/
ALTER TABLE "OPSOSYSTEM"."CONTRACT" DROP CONSTRAINT "FK_PHONE_NUMBERS_CONTRACTS"
/
ALTER TABLE "OPSOSYSTEM"."TARIF_PRICE_HISTORY" DROP CONSTRAINT "FK_tarif_price_history"
/
DROP TABLE "OPSOSYSTEM"."TARIF_OPTION_LINK"
/
DROP TABLE "OPSOSYSTEM"."EXCLUDE_OPTION"
/
DROP TABLE "OPSOSYSTEM"."CLIENT"
/
DROP TABLE "OPSOSYSTEM"."INCLUDE_OPTION"
/
DROP TABLE "OPSOSYSTEM"."TARIF"
/
DROP TABLE "OPSOSYSTEM"."CONTRACT"
/
DROP TABLE "OPSOSYSTEM"."OPTION"
/
DROP TABLE "OPSOSYSTEM"."TARIF_PRICE_HISTORY"
/
DROP TABLE "OPSOSYSTEM"."PHONE_NUMBER"
/
CREATE TABLE "OPSOSYSTEM"."OPTION" (
	"id" NUMBER ( 5 ) DEFAULT UID NOT NULL,
	"price" NUMBER ( 5, 2 ) NOT NULL,
	"add_coast" NUMBER ( 5, 2 ) NOT NULL,
	"active" CHAR ( 1 ) DEFAULT 'Y' NOT NULL,
	CONSTRAINT "TC_OPTIONS" UNIQUE ("id"),
	CONSTRAINT "PK_OPTIONS" PRIMARY KEY ("id")
	)
/
CREATE TABLE "OPSOSYSTEM"."CONTRACT" (
	"id" NUMBER ( 5 ) DEFAULT UID NOT NULL,
	"client_id" NUMBER ( 5 ) NOT NULL,
	"tarif_id" NUMBER ( 5 ) NOT NULL,
	"phone_number" NCHAR ( 12 ) NOT NULL,
	"phone_number_id" NUMBER ( 5 ) NOT NULL,
	CONSTRAINT "PK_CONTRACTS" PRIMARY KEY ("phone_number_id", "phone_number", "tarif_id", "client_id", "id")
	) TABLESPACE "USERS"
/
CREATE TABLE "OPSOSYSTEM"."TARIF_OPTION_LINK" (
	"id" NUMBER ( 5 ) NOT NULL,
	"tarif_id" NUMBER ( 5 ) NOT NULL,
	CONSTRAINT "PK_TARIFS_OPTIONS_LINK" PRIMARY KEY ("tarif_id", "id")
	)
/
CREATE TABLE "OPSOSYSTEM"."TARIF" (
	"id" NUMBER ( 5 ) DEFAULT UID NOT NULL,
	"name" VARCHAR2 ( 255 ) NOT NULL,
	"price" NUMBER ( 5, 2 ) NOT NULL,
	"isdeleted" CHAR ( 1 ) DEFAULT 'N' NOT NULL,
	CONSTRAINT "PK_TARIFS" PRIMARY KEY ("id"),
	CONSTRAINT "TC_TARIFS" UNIQUE ("id")
	) TABLESPACE "USERS"
/
CREATE TABLE "OPSOSYSTEM"."EXCLUDE_OPTION" (
	"parent_option_id" NUMBER ( 5 ) NOT NULL,
	"child_option_id" NUMBER ( 5 ) NOT NULL,
	CONSTRAINT "PK_exclude_option14" PRIMARY KEY ("child_option_id", "parent_option_id")
	)
/
CREATE TABLE "OPSOSYSTEM"."CLIENT" (
	"id" NUMBER ( 5 ) DEFAULT UID NOT NULL,
	"firstname" NUMBER ( 5 ) NOT NULL,
	"secondname" VARCHAR2 ( 50 ) NOT NULL,
	"birthdate" DATE NOT NULL,
	"pass_serias" VARCHAR2 ( 4 ) NOT NULL,
	"pass_number" VARCHAR2 ( 6 ) NOT NULL,
	"pass_issued_by" VARCHAR2 ( 255 ) NOT NULL,
	"pass_issued_date" DATE NOT NULL,
	"email" VARCHAR2 ( 50 ) NOT NULL,
	"pwd" VARCHAR2 ( 255 ) NOT NULL,
	CONSTRAINT "PK_CLIENTS" PRIMARY KEY ("id")
	) TABLESPACE "USERS"
/
CREATE TABLE "OPSOSYSTEM"."PHONE_NUMBER" (
	"id" NUMBER ( 5 ) DEFAULT UID NOT NULL,
	"phone_number" NCHAR ( 12 ) NOT NULL,
	"isused" CHAR ( 1 ) DEFAULT 'N' NOT NULL,
	"contract_id" NUMBER ( 5 ),
	CONSTRAINT "PK_phone_number" PRIMARY KEY ("id"),
	CONSTRAINT "TC_PHONE_NUMBERS" UNIQUE ("phone_number")
	) TABLESPACE "USERS"
/
CREATE TABLE "OPSOSYSTEM"."TARIF_PRICE_HISTORY" (
	"id" NUMBER ( 5 ) NOT NULL,
	"data" DATE NOT NULL,
	"tarif_id" NUMBER ( 5 ) NOT NULL,
	CONSTRAINT "PK_tarif_price_history" PRIMARY KEY ("tarif_id")
	)
/
CREATE TABLE "OPSOSYSTEM"."INCLUDE_OPTION" (
	"parent_option_id" NUMBER ( 5 ) NOT NULL,
	"child_option_id" NUMBER ( 5 ) NOT NULL,
	CONSTRAINT "PK_include_option" PRIMARY KEY ("child_option_id", "parent_option_id")
	)
/
ALTER TABLE "OPSOSYSTEM"."TARIF_OPTION_LINK" ADD ( CONSTRAINT "FK_TARIFS_TARIFS_OPTIONS_LINK" FOREIGN KEY ("id") REFERENCES "OPSOSYSTEM"."OPTION" ("id"))
/
ALTER TABLE "OPSOSYSTEM"."TARIF_OPTION_LINK" ADD ( CONSTRAINT "FK_OPTIONS_TARIFS_OPTIONS_LINK" FOREIGN KEY ("tarif_id") REFERENCES "OPSOSYSTEM"."TARIF" ("id"))
/
ALTER TABLE "OPSOSYSTEM"."EXCLUDE_OPTION" ADD ( CONSTRAINT "FK_exclude_option19" FOREIGN KEY ("parent_option_id") REFERENCES "OPSOSYSTEM"."OPTION" ("id"))
/
ALTER TABLE "OPSOSYSTEM"."EXCLUDE_OPTION" ADD ( CONSTRAINT "FK_exclude_option20" FOREIGN KEY ("child_option_id") REFERENCES "OPSOSYSTEM"."OPTION" ("id"))
/
ALTER TABLE "OPSOSYSTEM"."INCLUDE_OPTION" ADD ( CONSTRAINT "FK_include_option" FOREIGN KEY ("parent_option_id") REFERENCES "OPSOSYSTEM"."OPTION" ("id"))
/
ALTER TABLE "OPSOSYSTEM"."CONTRACT" ADD ( CONSTRAINT "FK_CLIENTS_CONTRACTS" FOREIGN KEY ("client_id") REFERENCES "OPSOSYSTEM"."CLIENT" ("id"))
/
ALTER TABLE "OPSOSYSTEM"."CONTRACT" ADD ( CONSTRAINT "FK_TARIFS_CONTRACTS" FOREIGN KEY ("tarif_id") REFERENCES "OPSOSYSTEM"."TARIF" ("id"))
/
ALTER TABLE "OPSOSYSTEM"."CONTRACT" ADD ( CONSTRAINT "FK_contract21" FOREIGN KEY ("phone_number_id") REFERENCES "OPSOSYSTEM"."PHONE_NUMBER" ("id"))
/
ALTER TABLE "OPSOSYSTEM"."CONTRACT" ADD ( CONSTRAINT "FK_PHONE_NUMBERS_CONTRACTS" FOREIGN KEY ("phone_number") REFERENCES "OPSOSYSTEM"."PHONE_NUMBER" ("phone_number"))
/
ALTER TABLE "OPSOSYSTEM"."TARIF_PRICE_HISTORY" ADD ( CONSTRAINT "FK_tarif_price_history" FOREIGN KEY ("tarif_id") REFERENCES "OPSOSYSTEM"."TARIF" ("id"))
/

