ALTER TABLE "OPSOSYSTEM"."INCLUDE_OPTION" DROP CONSTRAINT "FK_include_option"
/
ALTER TABLE "OPSOSYSTEM"."EXCLUDE_OPTION" DROP CONSTRAINT "FK_exclude_option19"
/
ALTER TABLE "OPSOSYSTEM"."EXCLUDE_OPTION" DROP CONSTRAINT "FK_exclude_option20"
/
ALTER TABLE "OPSOSYSTEM"."TARIFFS_OPTIONS_LINK" DROP CONSTRAINT "FKTARIFFSTARIFFSOPTIONSLINK"
/
ALTER TABLE "OPSOSYSTEM"."TARIFFS_OPTIONS_LINK" DROP CONSTRAINT "FKOPTIONSTARIFFSOPTIONSLINK"
/
ALTER TABLE "OPSOSYSTEM"."TARIFFS_PRICES_HISTORY" DROP CONSTRAINT "FK_TARIFFS_PRICES_HISTORY"
/
ALTER TABLE "OPSOSYSTEM"."CONTRACTS" DROP CONSTRAINT "FK_CLIENTS_CONTRACTS"
/
ALTER TABLE "OPSOSYSTEM"."CONTRACTS" DROP CONSTRAINT "FK_CONTRACTS25"
/
ALTER TABLE "OPSOSYSTEM"."CONTRACTS" DROP CONSTRAINT "FK_TARIFFS_CONTRACTS"
/
ALTER TABLE "OPSOSYSTEM"."PHONE_NUMBERS" DROP CONSTRAINT "FK_PHONE_NUMBERS"
/
DROP TABLE "OPSOSYSTEM"."TARIFFS"
/
DROP TABLE "OPSOSYSTEM"."CLIENT"
/
DROP TABLE "OPSOSYSTEM"."INCLUDE_OPTION"
/
DROP TABLE "OPSOSYSTEM"."EXCLUDE_OPTION"
/
DROP TABLE "OPSOSYSTEM"."TARIFFS_OPTIONS_LINK"
/
DROP TABLE "OPSOSYSTEM"."OPTION"
/
DROP TABLE "OPSOSYSTEM"."TARIFFS_PRICES_HISTORY"
/
DROP TABLE "OPSOSYSTEM"."CONTRACTS"
/
DROP TABLE "OPSOSYSTEM"."PHONE_NUMBERS"
/
CREATE TABLE "OPSOSYSTEM"."OPTION" (
	"id" NUMBER ( 5 ) DEFAULT UID NOT NULL,
	"price" NUMBER ( 5, 2 ) NOT NULL,
	"add_coast" NUMBER ( 5, 2 ) NOT NULL,
	"active" CHAR ( 1 ) DEFAULT 'Y' NOT NULL,
	CONSTRAINT "TC_OPTIONS" UNIQUE ("id"),
	CONSTRAINT "PK_OPTIONS" PRIMARY KEY ("id")
	)
/
CREATE TABLE "OPSOSYSTEM"."CONTRACTS" (
	"ID" NUMBER ( 5 ) DEFAULT UID NOT NULL,
	"CLIENT_ID" NUMBER ( 5 ) NOT NULL,
	"TARIFF_ID" NUMBER ( 5 ) NOT NULL,
	"PHONE_NUMBER_ID" NUMBER ( 5 ) NOT NULL,
	CONSTRAINT "PK_CONTRACTS" PRIMARY KEY ("TARIFF_ID", "CLIENT_ID", "ID")
	) TABLESPACE "USERS"
/
CREATE TABLE "OPSOSYSTEM"."TARIFFS_OPTIONS_LINK" (
	"ID" NUMBER ( 5 ) NOT NULL,
	"TARIFF_ID" NUMBER ( 5 ) NOT NULL,
	CONSTRAINT "PK_TARIFFS_OPTIONS_LINK" PRIMARY KEY ("TARIFF_ID", "ID")
	)
/
CREATE TABLE "OPSOSYSTEM"."TARIFFS" (
	"ID" NUMBER ( 5 ) DEFAULT UID NOT NULL,
	"NAME" VARCHAR2 ( 255 ) NOT NULL,
	"PRICE" NUMBER ( 5, 2 ) NOT NULL,
	"ISDELETED" CHAR ( 1 ) DEFAULT 'N' NOT NULL,
	CONSTRAINT "PK_TARIFFS" PRIMARY KEY ("ID")
	) TABLESPACE "USERS"
/
CREATE TABLE "OPSOSYSTEM"."EXCLUDE_OPTION" (
	"parent_option_id" NUMBER ( 5 ) NOT NULL,
	"child_option_id" NUMBER ( 5 ) NOT NULL,
	CONSTRAINT "PK_exclude_option14" PRIMARY KEY ("child_option_id", "parent_option_id")
	)
/
CREATE TABLE "OPSOSYSTEM"."CLIENT" (
	"id" NUMBER ( 5 ) DEFAULT UID NOT NULL,
	"firstname" NUMBER ( 5 ) NOT NULL,
	"secondname" VARCHAR2 ( 50 ) NOT NULL,
	"birthdate" DATE NOT NULL,
	"pass_serias" VARCHAR2 ( 4 ) NOT NULL,
	"pass_number" VARCHAR2 ( 6 ) NOT NULL,
	"pass_issued_by" VARCHAR2 ( 255 ) NOT NULL,
	"pass_issued_date" DATE NOT NULL,
	"email" VARCHAR2 ( 50 ) NOT NULL,
	"pwd" VARCHAR2 ( 255 ) NOT NULL,
	CONSTRAINT "PK_CLIENTS" PRIMARY KEY ("id")
	) TABLESPACE "USERS"
/
CREATE TABLE "OPSOSYSTEM"."PHONE_NUMBERS" (
	"ID" NUMBER ( 5 ) DEFAULT UID NOT NULL,
	"PHONE_NUMBER" NCHAR ( 12 ) NOT NULL,
	"ISSUED" CHAR ( 1 ) DEFAULT 'N' NOT NULL,
	"TARIFF_ID" NUMBER ( 5 ) NOT NULL,
	CONSTRAINT "TC_PHONE_NUMBERS" UNIQUE ("PHONE_NUMBER"),
	CONSTRAINT "PK_PHONE_NUMBERS" PRIMARY KEY ("ID")
	) TABLESPACE "USERS"
/
CREATE TABLE "OPSOSYSTEM"."TARIFFS_PRICES_HISTORY" (
	"ID" NUMBER ( 5 ) NOT NULL,
	"TARIFF_ID" NUMBER ( 5 ) NOT NULL,
	"DATE" DATE NOT NULL,
	"PRICE" NUMBER ( 5, 2 ) NOT NULL,
	CONSTRAINT "PK_TARIFFS_PRICES_HISTORY" PRIMARY KEY ("TARIFF_ID", "ID")
	)
/
CREATE TABLE "OPSOSYSTEM"."INCLUDE_OPTION" (
	"parent_option_id" NUMBER ( 5 ) NOT NULL,
	"child_option_id" NUMBER ( 5 ) NOT NULL,
	CONSTRAINT "PK_include_option" PRIMARY KEY ("child_option_id", "parent_option_id")
	)
/
ALTER TABLE "OPSOSYSTEM"."INCLUDE_OPTION" ADD ( CONSTRAINT "FK_include_option" FOREIGN KEY ("parent_option_id") REFERENCES "OPSOSYSTEM"."OPTION" ("id"))
/
ALTER TABLE "OPSOSYSTEM"."EXCLUDE_OPTION" ADD ( CONSTRAINT "FK_exclude_option19" FOREIGN KEY ("parent_option_id") REFERENCES "OPSOSYSTEM"."OPTION" ("id"))
/
ALTER TABLE "OPSOSYSTEM"."EXCLUDE_OPTION" ADD ( CONSTRAINT "FK_exclude_option20" FOREIGN KEY ("child_option_id") REFERENCES "OPSOSYSTEM"."OPTION" ("id"))
/
ALTER TABLE "OPSOSYSTEM"."TARIFFS_OPTIONS_LINK" ADD ( CONSTRAINT "FKTARIFFSTARIFFSOPTIONSLINK" FOREIGN KEY ("ID") REFERENCES "OPSOSYSTEM"."OPTION" ("id"))
/
ALTER TABLE "OPSOSYSTEM"."TARIFFS_OPTIONS_LINK" ADD ( CONSTRAINT "FKOPTIONSTARIFFSOPTIONSLINK" FOREIGN KEY ("TARIFF_ID") REFERENCES "OPSOSYSTEM"."TARIFFS" ("ID"))
/
ALTER TABLE "OPSOSYSTEM"."TARIFFS_PRICES_HISTORY" ADD ( CONSTRAINT "FK_TARIFFS_PRICES_HISTORY" FOREIGN KEY ("TARIFF_ID") REFERENCES "OPSOSYSTEM"."TARIFFS" ("ID"))
/
ALTER TABLE "OPSOSYSTEM"."CONTRACTS" ADD ( CONSTRAINT "FK_CLIENTS_CONTRACTS" FOREIGN KEY ("CLIENT_ID") REFERENCES "OPSOSYSTEM"."CLIENT" ("id"))
/
ALTER TABLE "OPSOSYSTEM"."CONTRACTS" ADD ( CONSTRAINT "FK_CONTRACTS25" FOREIGN KEY ("PHONE_NUMBER_ID") REFERENCES "OPSOSYSTEM"."PHONE_NUMBERS" ("ID"))
/
ALTER TABLE "OPSOSYSTEM"."CONTRACTS" ADD ( CONSTRAINT "FK_TARIFFS_CONTRACTS" FOREIGN KEY ("TARIFF_ID") REFERENCES "OPSOSYSTEM"."TARIFFS" ("ID"))
/
ALTER TABLE "OPSOSYSTEM"."PHONE_NUMBERS" ADD ( CONSTRAINT "FK_PHONE_NUMBERS" FOREIGN KEY ("TARIFF_ID") REFERENCES "OPSOSYSTEM"."CONTRACTS" ("TARIFF_ID", "CLIENT_ID", "ID"))
/

