-- USER SQL
CREATE USER opsosystem IDENTIFIED BY opsos
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";

-- ROLES
GRANT "CONNECT" TO opsosystem ;

-- SYSTEM PRIVILEGES
GRANT DROP ANY TRIGGER TO opsosystem ;
GRANT CREATE USER TO opsosystem ;
GRANT UPDATE ANY TABLE TO opsosystem ;
GRANT CREATE TRIGGER TO opsosystem ;
GRANT CREATE TABLESPACE TO opsosystem ;
GRANT CREATE SEQUENCE TO opsosystem ;
GRANT SELECT ANY SEQUENCE TO opsosystem ;
GRANT CREATE TABLE TO opsosystem ;
GRANT SELECT ANY TABLE TO opsosystem ;
GRANT DROP USER TO opsosystem ;
GRANT DROP ANY TYPE TO opsosystem ;
GRANT CREATE ANY VIEW TO opsosystem ;
GRANT CREATE ANY TRIGGER TO opsosystem ;
GRANT DROP ANY TABLE TO opsosystem ;
GRANT DROP ANY VIEW TO opsosystem ;
GRANT ALTER ANY TRIGGER TO opsosystem ;
GRANT CREATE SYNONYM TO opsosystem ;
GRANT ALTER ANY TABLE TO opsosystem ;
GRANT CREATE VIEW TO opsosystem ;
GRANT CREATE TYPE TO opsosystem ;
GRANT CREATE ROLE TO opsosystem ;
GRANT CREATE ANY TABLE TO opsosystem ;
GRANT CREATE SESSION TO opsosystem ;
GRANT DROP ANY SYNONYM TO opsosystem ;
GRANT DROP TABLESPACE TO opsosystem ;
GRANT CREATE ANY TYPE TO opsosystem ;

-- QUOTAS
ALTER USER opsosystem QUOTA UNLIMITED ON USERS;
