CREATE SEQUENCE OPSYSTEM.TARIFFS_ID_SEQ INCREMENT BY 1 START WITH 0 MAXVALUE 1000 MINVALUE 0 ORDER;
CREATE SEQUENCE OPSYSTEM.OPTIONS_ID_SEQ INCREMENT BY 1 START WITH 0 MAXVALUE 10000 MINVALUE 0 ORDER;

