ALTER TABLE "OPSYSTEM"."INCLUDE_OPTION" DROP CONSTRAINT "FK_include_option"
/
ALTER TABLE "OPSYSTEM"."EXCLUDE_OPTION" DROP CONSTRAINT "FK_exclude_option19"
/
ALTER TABLE "OPSYSTEM"."EXCLUDE_OPTION" DROP CONSTRAINT "FK_exclude_option20"
/
ALTER TABLE "OPSYSTEM"."TARIFFS_OPTIONS_LINK" DROP CONSTRAINT "FKTARIFFSTARIFFSOPTIONSLINK"
/
ALTER TABLE "OPSYSTEM"."TARIFFS_OPTIONS_LINK" DROP CONSTRAINT "FKOPTIONSTARIFFSOPTIONSLINK"
/
ALTER TABLE "OPSYSTEM"."TARIFFS_PRICES_HISTORY" DROP CONSTRAINT "FK_TARIFFS_PRICES_HISTORY"
/
ALTER TABLE "OPSYSTEM"."CONTRACTS" DROP CONSTRAINT "FK_CLIENTS_CONTRACTS"
/
ALTER TABLE "OPSYSTEM"."CONTRACTS" DROP CONSTRAINT "FK_CONTRACTS25"
/
ALTER TABLE "OPSYSTEM"."CONTRACTS" DROP CONSTRAINT "FK_TARIFFS_CONTRACTS"
/
ALTER TABLE "OPSYSTEM"."PHONE_NUMBERS" DROP CONSTRAINT "FK_PHONE_NUMBERS"
/
DROP TABLE "OPSYSTEM"."TARIFFS"
/
DROP TABLE "OPSYSTEM"."CLIENT"
/
DROP TABLE "OPSYSTEM"."INCLUDE_OPTION"
/
DROP TABLE "OPSYSTEM"."EXCLUDE_OPTION"
/
DROP TABLE "OPSYSTEM"."TARIFFS_OPTIONS_LINK"
/
DROP TABLE "OPSYSTEM"."OPTION"
/
DROP TABLE "OPSYSTEM"."TARIFFS_PRICES_HISTORY"
/
DROP TABLE "OPSYSTEM"."CONTRACTS"
/
DROP TABLE "OPSYSTEM"."PHONE_NUMBERS"
/
CREATE TABLE "OPSYSTEM"."OPTION" (
	"ID" NUMBER ( 5 ) DEFAULT UID NOT NULL,
	"PRICE" NUMBER ( 10 ) NOT NULL,
	"ADD_COAST" NUMBER ( 10 ) NOT NULL,
	"ACTIVE" CHAR ( 1 ) DEFAULT 'Y' NOT NULL,
	CONSTRAINT "TC_OPTIONS" UNIQUE ("ID"),
	CONSTRAINT "PK_OPTIONS" PRIMARY KEY ("ID")
	)
/
CREATE TABLE "OPSYSTEM"."CONTRACTS" (
	"ID" NUMBER ( 5 ) DEFAULT UID NOT NULL,
	"CLIENT_ID" NUMBER ( 5 ) NOT NULL,
	"TARIFF_ID" NUMBER ( 5 ) NOT NULL,
	"PHONE_NUMBER_ID" NUMBER ( 5 ) NOT NULL,
	CONSTRAINT "PK_CONTRACTS" PRIMARY KEY ("TARIFF_ID", "CLIENT_ID", "ID")
	) TABLESPACE "USERS"
/
CREATE TABLE "OPSYSTEM"."TARIFFS_OPTIONS_LINK" (
	"ID" NUMBER ( 5 ) NOT NULL,
	"TARIFF_ID" NUMBER ( 5 ) NOT NULL,
	CONSTRAINT "PK_TARIFFS_OPTIONS_LINK" PRIMARY KEY ("TARIFF_ID", "ID")
	)
/
CREATE TABLE "OPSYSTEM"."TARIFFS" (
	"ID" NUMBER ( 5 ) DEFAULT UID NOT NULL,
	"NAME" VARCHAR2 ( 255 ) NOT NULL,
	"PRICE" NUMBER ( 10 ) NOT NULL,
	"ISDELETED" CHAR ( 1 ) DEFAULT 'N' NOT NULL,
	CONSTRAINT "PK_TARIFFS" PRIMARY KEY ("ID")
	) TABLESPACE "USERS"
/
CREATE TABLE "OPSYSTEM"."EXCLUDE_OPTION" (
	"ID" NUMBER ( 5 ) NOT NULL,
	"CHILD_OPTION_ID" NUMBER ( 5 ) NOT NULL,
	CONSTRAINT "PK_exclude_option14" PRIMARY KEY ("CHILD_OPTION_ID", "ID")
	)
/
CREATE TABLE "OPSYSTEM"."CLIENT" (
	"ID" NUMBER ( 5 ) DEFAULT UID NOT NULL,
	"FIRSTNAME" NUMBER ( 5 ) NOT NULL,
	"SECONDNAME" VARCHAR2 ( 50 ) NOT NULL,
	"BIRTHDATE" DATE NOT NULL,
	"PASS_SERIAS" VARCHAR2 ( 4 ) NOT NULL,
	"PASS_NUMBER" VARCHAR2 ( 6 ) NOT NULL,
	"PASS_ISSUED_BY" VARCHAR2 ( 255 ) NOT NULL,
	"PASS_ISSUED_DATE" DATE NOT NULL,
	"EMAIL" VARCHAR2 ( 50 ) NOT NULL,
	"PWD" VARCHAR2 ( 255 ) NOT NULL,
	CONSTRAINT "PK_CLIENTS" PRIMARY KEY ("ID")
	) TABLESPACE "USERS"
/
CREATE TABLE "OPSYSTEM"."PHONE_NUMBERS" (
	"ID" NUMBER ( 5 ) DEFAULT UID NOT NULL,
	"PHONE_NUMBER" NCHAR ( 12 ) NOT NULL,
	"ISSUED" CHAR ( 1 ) DEFAULT 'N' NOT NULL,
	"TARIFF_ID" NUMBER ( 5 ) NOT NULL,
	CONSTRAINT "TC_PHONE_NUMBERS" UNIQUE ("PHONE_NUMBER"),
	CONSTRAINT "PK_PHONE_NUMBERS" PRIMARY KEY ("ID")
	) TABLESPACE "USERS"
/
CREATE TABLE "OPSYSTEM"."TARIFFS_PRICES_HISTORY" (
	"ID" NUMBER ( 5 ) NOT NULL,
	"TARIFF_ID" NUMBER ( 5 ) NOT NULL,
	"DATE" DATE NOT NULL,
	"PRICE" NUMBER ( 10 ) NOT NULL,
	CONSTRAINT "PK_TARIFFS_PRICES_HISTORY" PRIMARY KEY ("TARIFF_ID", "ID")
	)
/
CREATE TABLE "OPSYSTEM"."INCLUDE_OPTION" (
	"ID" NUMBER ( 5 ) NOT NULL,
	"CHILD_OPTION_ID" NUMBER ( 5 ) NOT NULL,
	CONSTRAINT "PK_include_option" PRIMARY KEY ("CHILD_OPTION_ID", "ID")
	)
/
ALTER TABLE "OPSYSTEM"."INCLUDE_OPTION" ADD ( CONSTRAINT "FK_include_option" FOREIGN KEY ("ID") REFERENCES "OPSYSTEM"."OPTION" ("ID"))
/
ALTER TABLE "OPSYSTEM"."EXCLUDE_OPTION" ADD ( CONSTRAINT "FK_exclude_option19" FOREIGN KEY ("ID") REFERENCES "OPSYSTEM"."OPTION" ("ID"))
/
ALTER TABLE "OPSYSTEM"."EXCLUDE_OPTION" ADD ( CONSTRAINT "FK_exclude_option20" FOREIGN KEY ("CHILD_OPTION_ID") REFERENCES "OPSYSTEM"."OPTION" ("ID"))
/
ALTER TABLE "OPSYSTEM"."TARIFFS_OPTIONS_LINK" ADD ( CONSTRAINT "FKTARIFFSTARIFFSOPTIONSLINK" FOREIGN KEY ("ID") REFERENCES "OPSYSTEM"."OPTION" ("ID"))
/
ALTER TABLE "OPSYSTEM"."TARIFFS_OPTIONS_LINK" ADD ( CONSTRAINT "FKOPTIONSTARIFFSOPTIONSLINK" FOREIGN KEY ("TARIFF_ID") REFERENCES "OPSYSTEM"."TARIFFS" ("ID"))
/
ALTER TABLE "OPSYSTEM"."TARIFFS_PRICES_HISTORY" ADD ( CONSTRAINT "FK_TARIFFS_PRICES_HISTORY" FOREIGN KEY ("TARIFF_ID") REFERENCES "OPSYSTEM"."TARIFFS" ("ID"))
/
ALTER TABLE "OPSYSTEM"."CONTRACTS" ADD ( CONSTRAINT "FK_CLIENTS_CONTRACTS" FOREIGN KEY ("CLIENT_ID") REFERENCES "OPSYSTEM"."CLIENT" ("ID"))
/
ALTER TABLE "OPSYSTEM"."CONTRACTS" ADD ( CONSTRAINT "FK_CONTRACTS25" FOREIGN KEY ("PHONE_NUMBER_ID") REFERENCES "OPSYSTEM"."PHONE_NUMBERS" ("ID"))
/
ALTER TABLE "OPSYSTEM"."CONTRACTS" ADD ( CONSTRAINT "FK_TARIFFS_CONTRACTS" FOREIGN KEY ("TARIFF_ID") REFERENCES "OPSYSTEM"."TARIFFS" ("ID"))
/
ALTER TABLE "OPSYSTEM"."PHONE_NUMBERS" ADD ( CONSTRAINT "FK_PHONE_NUMBERS" FOREIGN KEY ("TARIFF_ID") REFERENCES "OPSYSTEM"."CONTRACTS" ("TARIFF_ID", "CLIENT_ID", "ID"))
/

