-- USER SQL
CREATE USER OPSYSTEM IDENTIFIED BY opsys
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";

-- ROLES
GRANT "CONNECT" TO OPSYSTEM ;

-- SYSTEM PRIVILEGES
GRANT DROP ANY TRIGGER TO OPSYSTEM ;
GRANT CREATE USER TO OPSYSTEM ;
GRANT UPDATE ANY TABLE TO OPSYSTEM ;
GRANT CREATE TRIGGER TO OPSYSTEM ;
GRANT CREATE TABLESPACE TO OPSYSTEM ;
GRANT CREATE SEQUENCE TO OPSYSTEM ;
GRANT SELECT ANY SEQUENCE TO OPSYSTEM ;
GRANT CREATE TABLE TO OPSYSTEM ;
GRANT SELECT ANY TABLE TO OPSYSTEM ;
GRANT DROP USER TO OPSYSTEM ;
GRANT DROP ANY TYPE TO OPSYSTEM ;
GRANT CREATE ANY VIEW TO OPSYSTEM ;
GRANT CREATE ANY TRIGGER TO OPSYSTEM ;
GRANT DROP ANY TABLE TO OPSYSTEM ;
GRANT DROP ANY VIEW TO OPSYSTEM ;
GRANT ALTER ANY TRIGGER TO OPSYSTEM ;
GRANT CREATE SYNONYM TO OPSYSTEM ;
GRANT ALTER ANY TABLE TO OPSYSTEM ;
GRANT CREATE VIEW TO OPSYSTEM ;
GRANT CREATE TYPE TO OPSYSTEM ;
GRANT CREATE ROLE TO OPSYSTEM ;
GRANT CREATE ANY TABLE TO OPSYSTEM ;
GRANT CREATE SESSION TO OPSYSTEM ;
GRANT DROP ANY SYNONYM TO OPSYSTEM ;
GRANT DROP TABLESPACE TO OPSYSTEM ;
GRANT CREATE ANY TYPE TO OPSYSTEM ;

-- QUOTAS
ALTER USER OPSYSTEM QUOTA UNLIMITED ON USERS;
