INSERT INTO OPSYSTEM.OPTIONS(ID, NAME, PRICE, ADD_COAST) VALUES(NULL, 'OPTION #1', 1000, 100);
INSERT INTO OPSYSTEM.OPTIONS(ID, NAME, PRICE, ADD_COAST) VALUES(NULL, 'OPTION #2', 2000, 200);
INSERT INTO OPSYSTEM.OPTIONS(ID, NAME, PRICE, ADD_COAST) VALUES(NULL, 'OPTION #3', 3000, 300);
INSERT INTO OPSYSTEM.OPTIONS(ID, NAME, PRICE, ADD_COAST) VALUES(NULL, 'OPTION #4', 4000, 400);
INSERT INTO OPSYSTEM.OPTIONS(ID, NAME, PRICE, ADD_COAST) VALUES(NULL, 'OPTION #5', 5000, 500);
INSERT INTO OPSYSTEM.OPTIONS(ID, NAME, PRICE, ADD_COAST) VALUES(NULL, 'OPTION #6', 6000, 600);

SELECT * FROM OPSYSTEM.OPTIONS;
TRUNCATE TABLE OPSYSTEM.OPTIONS;

SELECT ID FROM OPSYSTEM.OPTIONS WHERE NAME LIKE 'OPTION #3';
SELECT ID FROM OPSYSTEM.OPTIONS WHERE NAME LIKE 'OPTION #5';

INSERT INTO OPSYSTEM.INCLUDE_OPTIONS VALUES(11, 13);

SELECT ID FROM OPSYSTEM.OPTIONS WHERE NAME LIKE 'OPTION #6';
SELECT ID FROM OPSYSTEM.OPTIONS WHERE NAME LIKE 'OPTION #1';
INSERT INTO OPSYSTEM.EXCLUDE_OPTIONS VALUES(14, 9);

DELETE FROM OPSYSTEM.INCLUDE_OPTIONS WHERE ID=6; 

update opsystem.rates set isdeleted='N';

INSERT INTO OPSYSTEM.PHONE_NUMBERS(PHONE_NUMBER) VALUES('9818420468');
INSERT INTO OPSYSTEM.PHONE_NUMBERS(PHONE_NUMBER) VALUES('9818420469');
INSERT INTO OPSYSTEM.PHONE_NUMBERS(PHONE_NUMBER) VALUES('9818420470');
INSERT INTO OPSYSTEM.PHONE_NUMBERS(PHONE_NUMBER) VALUES('9818420471');
INSERT INTO OPSYSTEM.PHONE_NUMBERS(PHONE_NUMBER) VALUES('9818420472');
INSERT INTO OPSYSTEM.PHONE_NUMBERS(PHONE_NUMBER) VALUES('9818420473');


INSERT INTO OPSYSTEM.OPSYSTEM_ROLES(NAME) VALUES('COMMON_USER');
INSERT INTO OPSYSTEM.OPSYSTEM_ROLES(NAME) VALUES('EMPLOYEE');

INSERT INTO OPSYSTEM.ACCOUNTS(LOGIN,PWD,ROLE_ID,PERSON_ID) VALUES('common','password',1,4);
INSERT INTO OPSYSTEM.ACCOUNTS(LOGIN,PWD,ROLE_ID,PERSON_ID) VALUES('operator','password',1,4);
UPDATE OPSYSTEM.ACCOUNTS SET role_id = 0 WHERE LOGIN LIKE 'common';

select * from opsystem.accounts where login like 'common';
